# Generated by Django 3.1.1 on 2023-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_feed_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='user_id',
        ),
        migrations.AddField(
            model_name='feed',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
