# Generated by Django 4.0.3 on 2023-05-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
